# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

normal_pdf <- function(x, m, s) {
    .Call(`_MVMR_CUE_normal_pdf`, x, m, s)
}

MVMRCUEfun <- function(gammahM, Gammah, se1M, se2) {
    .Call(`_MVMR_CUE_MVMRCUEfun`, gammahM, Gammah, se1M, se2)
}

MVMRCUEoverlapfun <- function(gammahM, Gammah, se1M, se2, Re, Eta) {
    .Call(`_MVMR_CUE_MVMRCUEoverlapfun`, gammahM, Gammah, se1M, se2, Re, Eta)
}

MVMRCUEIndepSample <- function(gammahM, Gammah, se1M, se2, opts = NULL) {
    .Call(`_MVMR_CUE_MVMRCUEIndepSample`, gammahM, Gammah, se1M, se2, opts)
}

MVMRCUE <- function(gammahM, Gammah, se1M, se2, Re, opts = NULL) {
    .Call(`_MVMR_CUE_MVMRCUE`, gammahM, Gammah, se1M, se2, Re, opts)
}

rcpparma_hello_world <- function() {
    .Call(`_MVMR_CUE_rcpparma_hello_world`)
}

rcpparma_outerproduct <- function(x) {
    .Call(`_MVMR_CUE_rcpparma_outerproduct`, x)
}

rcpparma_innerproduct <- function(x) {
    .Call(`_MVMR_CUE_rcpparma_innerproduct`, x)
}

rcpparma_bothproducts <- function(x) {
    .Call(`_MVMR_CUE_rcpparma_bothproducts`, x)
}

